### ISSUE TITLE
Tutorial: tutorial instructions window dismisses the menu bmp UI

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#109]
Tutorial has you 'lookat' a menu.  This works but the next tutorial instruction comes up immediately, and the menu bmp gets dismissed before you can look at it.

**Comment by grahamboree** [comment]
Note to future me:  This is caused by the createWindow interaction with the script stack.  The ExecuteScript call is creating a new thread with a new window that doesn't share a name with any other window, but for some reason it's being disabled in the heirarchy.  I have a feeling it's related to the code that clears windows when a script terminates...
