### ISSUE TITLE
Can't order more than one of the same thing from the bartender or the chef

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#125]
Repro:
Say "beer beer" to the bartender or "steak steak" to the chef.  They both only give you one instance of the food.

**Comment by jefforkin** [comment]
This is how the original TRG worked too.  Part of the problem is that someone could ask for a "cherry pie" and we use both of those key words to spawn items, and don't want two pies.  Also dont really want to encourage people to type beer as many times as they can in one line.  (though they do that anyway through multiple lines).

Someday it might be cool to leverage the AI system to do more sophisticated parsing, to understand input like "2 beers please".  But for now, we should just leave the system as-is, in terms of spawning multiple of the same item from one input.
