### ISSUE TITLE
Waitress's head explodes during chat

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#138]
Clark & Alec both said the waitress had laser eyes while chatting, possibly during lip sync animation.

**Comment by grahamboree** [comment]
Jeff and I just repro'd this.  

1.  Join a game with two clients open
2.  Quit the game to the main menu
3.  Start a new game with both clients
4.  Chat and observe the other player.

I got a lot of these spammed to the console when it happened, but Jeff didn't:
Quaternion To Matrix conversion failed because input Quaternion is invalid {-1.#QNAN0, -1.#QNAN0, -1.#QNAN0, -1.#QNAN0} l=-1.#QNAN0

No callstack.  A quick google of the error found a promising looking YouTube comment (of all things on the internet, this is the LAST place I'd expect to find some kind of useful information):

"Oh nevermind; the problem disappeared when I changed the parameter in the blend tree to 'speed' and then back to 'direction'... technology, huh?"
https://www.youtube.com/watch?v=MIDt4eIlv8c&lc=z13pwbv5nmj2cp20f231cjuhxzu1vdm33

**Comment by dwenger01** [comment]
I'm actually unable to repro this issue...  I followed the repro directions and am running 2 instances of trg pc builds.  Is this something that only appears in the web-player version?

**Comment by jefforkin** [comment]
No not webplayer.  Graham and I could repro it 100% today.  I connected two instances on my machine, one running through the Unity editor (set to a PC build), and one from an actual PC build.  The key is that you need to play, chat, then use the menu to quit, and start another multiplayer game, and chat again.  should see it.

**Comment by dwenger01** [comment]
Okay, I'm seeing it now in the webplayer...  I'll try to get it to happen the way you describe.

**Comment by dwenger01** [comment]
Still not seeing it when running via unity editor and actual pc build.  I'm on tips of master as of tonight.

So on Sunday I did a git clean of my repo ( "git clean -ffxd" )...  Does the build robot start with a completely clean/fresh repo when it makes the webplayer build?  Was your repo clean when you built and ran this earlier?

I wonder if maybe there is some anomalous file out there that's causing this... Just an idea...

**Comment by jefforkin** [comment]
I can try tomorrow (tues), doing a repro, then a git clean, and see if I still can get it.  Not sure if build bot does a clean.  can ask Graham tomorrow.

**Comment by dwenger01** [comment]
Sounds good.  After 20 minutes of testing I'm still not seeing it locally.  I only see it via the webplayer in firefox.

**Comment by grahamboree** [comment]
@dwenger01 The build script uses whatever's locally on my machine, so it's not doing a complete git clean before every build (otherwise the build would take over an hour, when it already takes 30 mins).  I just tried reproing this again, and I was able to, though I only saw the animation issue in the editor, and not in the standalone I built with the same code.  Maybe that's why you're not seeing it?

**Comment by dwenger01** [comment]
Interesting...  I've tried using the editor and a standalone together and can't repro it in that case.  The only time I ever saw an issue was running 2 webplayer versions in 2 instances of firefox.

**Comment by dwenger01** [comment]
Still not able to repro this problem consistently, and I'm not able to look at the animations in the .fbx with a .fbx viewer since it doesn't appear that the mesh data is included in the .fbx.  I will try figuring out how to import them into a completely new unity project to try to learn what might be causing the issue.

**Comment by jefforkin** [comment]
I'm going to reach out to Jason for help on this.

**Comment by jefforkin** [comment]
This was hopefully fixed by setting the Write Defaults checkbox to True on the gestureidle state in the IdleAndGestures sub-state machine.  Closing until we see evidence that a problem still exists.
