### ISSUE TITLE
Mouse off center in fullscreen

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#139]
Dan switched to fullscreen, and the mouse was off center (lower right I think), but still functional.

**Comment by tomaschko** [comment]
Tried to repro today and could not. Perhaps the toggle and reticle changes fixed any issues

**Comment by grahamboree** [comment]
Yeah this should be mitigated with the change to how interaction raycasts are generated.  They use the center point of the screen now instead of the mouse position.  The OSX webplayer was locking the mouse to the lower right for some reason, so the change to the raycast origin just totally avoids the problem.
