### ISSUE TITLE
Difficult to pick up the bill from the podium

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#149]
It's hard to notice when the bill is created and it's difficult to pick up from the podium. Often user will pick up the register instead - which is then hard to replace on the podium

**Comment by jefforkin** [comment]
I should explain why this one is assigned to Dave.  We would like to add the ability to optionally set the orientation of an object when it is spawned, so that bills could always spawn standing on an incline,  where they are easier to see and interact with.  Actually, this might be as simple as just adding a parent object to the bill in the prefab that orients it, but we'll need to make sure this does not break anything with associated scripts.

**Comment by jefforkin** [comment]
I added a parent object in the bill prefab to make the bill stand up straight.
