### ISSUE TITLE
LookAt zoom starts after delay

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#152]
When I run the tutorial, on the step where I lookat the bartender, sometimes the zoom does not start right away.  It seems like it starts when I manually rotate the camera to face the bartender more directly.  Then the zoom starts.

**Comment by dwenger01** [comment]
This may be fixed with my fixes for issue 126.  There was an issue in the camera manager in which the update for the look-at was always assuming it could rotate the correct amount.  In some cases the look-at won't be able to lerp all the way to the desired look-at vector (limitations in yaw or pitch for example).  When I detect that we are no longer rotating I call the rotation done and this will allow the zoom-in step to begin.

Let's verify if this is fixed with the solution to issue 126.

**Comment by jefforkin** [comment]
I synced and tested this a couple times in the tutorial.  It appears to be fixed, as far as I can tell.  Feel free to close it, unless you have any remaining concerns.

**Comment by dwenger01** [comment]
Excellent
