### ISSUE TITLE
Can't chat while sitting

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#175]
Experienced during playtest.  Sit and try to chat in multiplayer.  Not sure if singleplayer has issues too.

**Comment by dwenger01** [comment]
This is a problem because chatting is associated with the ControlSchemeWASD component, which gets disabled when you sit (so we can't enable chat while sitting).  I'm wondering if it makes sense to create a separate component for chatting so we can turn off movement, but still be able to chat.

Maybe we could move the management of enabling/disabling chat (focus swapping, etc.) out of the WASD component and into the ChatInterface instead?

I'd welcome your thoughts.

**Comment by grahamboree** [comment]
@dwenger01, I actually didn't see your comment until just now, but that's coincidentally exactly the fix I put in.  Great minds...etc... :D

**Comment by dwenger01** [comment]
Cool!  Good to know I'm on the same page as you Graham!
