### ISSUE TITLE
Camera is at player's feet

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#248]
After upgrading to Unity 5.2.1f1, when I run Restaurant, the camera is at the player's feet

**Comment by grahamboree** [comment]
In 5.2 they changed (fixed?) a few things regarding humanoid skeleton importing that are affecting where Unity thinks the camera node bone is.  The end result is that the origin for the skeleton is in the sternum of the character, and thus the camera vertical offset is only the distance from the sternum to the camera node.  

As a workaround, I've hard-coded the camera offset to work with the characters we have now, rather than trying to fix the import settings.  Jason would be better at troubleshooting this issue.
