### ISSUE TITLE
Lemelson: remove 2nd start menu screen

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#253]
Now that we no longer have a full-screen option, the 2nd menu screen is completely redundant (just one button that says "Start playing Young Inventor"). 

If it does not cause major technical issues, we should just launch right into the game from from the initial "School Life | Click here to play Young Inventor" screen

**Comment by grahamboree** [comment]
Initially I had the same reaction and tried to remove the second screen, however because we are doing things behind the scenes and in oscript (setting the role and config) when you hit the start button, I couldn't easily remove it.  I wasn't sure if it was worth spending time on, so I left it in.  There are a lot of complex startup procedures and order of operations to make sure we maintain after the change.  I could remove the screen in probably half a day.

**Comment by tomaschko** [comment]
OK I thought that might be the case. 1/2 day is too much, so I think you
made the right call. I'll close this one
