### ISSUE TITLE
Facilitator/Director account vs privileged audience member?

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#315]
Are facilitators a special kind of user account?
Are they just the person who created the room?
How does the idea of a facilitator work with the entertainment style of gameplay?

We need to answer these questions and task out the work necessary to implement the correct system.  Right now, facilitators are just developer accounts who are playing as spectators.

**Comment by jefforkin** [comment]
Facilitators will eventually be tied to user accounts.  It is a user with special privileges.

For current purposes, teachers will be facilitators.  TRG does not have a facilitator.  

In the future, I could imagine offering different game modes on the entertainment side where there are spectators with special privileges, like a Director.  How these privileges work needs more thought, because in some cases they are permanently associated with your account, and in others they are granted per session.

**Comment by grahamboree** [comment]
Okay, that sounds good.  I'm changing this to be a task to determining that relationship: whether we want privileged audience members per game, whether it's an account setting, or some combination of the two.
