### ISSUE TITLE
Add Facilitator user type

### ISSUE THREAD

**Issue by grahamboree** [giantotter/giantotter_public#316]
Facilitators are special types of users, so the user account needs to have this data associated with it.
The Unity side also needs to read this information when the user logs in.

**Comment by jefforkin** [comment]
I think we need to do a design pass on this with me, Graham, and Dan.  Because we want an implementation that supports something like:
- user accounts have privileges associated to a specific group.  like the teacher of one class.
- facilitator for an educational game can be anyone with the right privileges, because there might be a teacher and an assist teacher, but only one is facilitator at a time.
- some games, like TRG may have no facilitator at all.
- some variations of TRG/improv may have a special spectator, like a Director.  But those rights are not permanent.
- We may want to indicate the Facilitator with a different title for different experiences -- Director, Teacher, Facilitator, etc.

In general, this needs more thought.
