### ISSUE TITLE
When typing in spectator chat, my cursor fails to advance as I type

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#360]
As a result, each letter is appended to the beginning of the sentence, rather than the end, and each word is spelled backwards

Cannot repro reliably... Usually occurs after extended play (more than a few minutes)

Specs attached
![screen shot 2015-12-18 at 2 51 50 pm](https://cloud.githubusercontent.com/assets/4423632/11905887/fb862012-a596-11e5-823f-fca97abc0cc7.png)

**Comment by tomaschko** [comment]
Repro: 
- Hold “shift+cmd” then hit "left arrow" to highlight an entire row of text to delete
- when i do that it sticks the cursor to the beginning of the line so that i type backwards
- i can reverse it with "shift+CMD" and "right arrow"

**Comment by grahamboree** [comment]
This only happens in standalone builds on OSX and is a bug in Unity.  There's also a lot of non-standard behavior related to selecting text with the keyboard in input fields in general on OSX...

https://fogbugz.unity3d.com/default.asp?765990_7rc4lvuf4emoosj9

**Comment by grahamboree** [comment]
Unity just got back to me.  Apparently my bug was a dupe and it's already being addressed.  No word on the release it will be fixed in though...  

Here's the issue they said mine was a dupe of: https://issuetracker.unity3d.com/issues/osx-directional-keys-dont-work-with-inputfield-in-standalone-but-work-inside-the-editor
