### ISSUE TITLE
Multiple games receiving the same room GUID from roombot

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#427]
Dave reports that he gets the same room GUID in multiple games, unless he changes group code.

**Comment by dwenger01** [comment]
Started up a multiplayer session with just 1 player using group code 131.  Did some testing and then exited the session.

About 5 minutes later started a new multiplayer session with just 1 player using the same group code.  I ended up getting the same GUID for the room.

Exited and started a new session with group code 232.  A new GUID was generated for the room.

Seems like there might be an issue with a room not being deleted once it's empty, so that a subsequent join with the same group code attaches to the same room instance.

**Comment by jefforkin** [comment]
We have not been able to repro this, but I have implemented fail safes that should detect rooms with stale data, and remove them before returning a room to the user.  So the situation Dave encountered should never happen again.

The only caveat is is the IRC library that powers roombot fails to detect that a user is no longer in a channel, then we would still have problems.  If we see this case, then we should switch to a different python IRC package.
