### ISSUE TITLE
Canned dialog tool supports building feedback in parts

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#497]
Build feedback message in parts (perhaps via checklist), during the conversation

**Comment by tomaschko** [comment]
1st pass: eliminate the need to copy / paste / send each element of feedback separately so that the feedback message can be assembled more quickly at the end of the game

(here are a few thoughts off the top of my head. i don't know what will be easy / possible so feel free to suggest other approaches)
- feedback _can_ be driven by a separate file, if needed - easy to open it in a separate tab
- my best current idea for the design is a checklist model - tick off all of the comments to include as feedback, then one button copies them into one large multi-line message that can be pasted and sent in slack
- ".feedback", "./feedback", and the 3 "info ..." items are pre-selected so that they automatically copy into the message

for context, in the future we will likely evolve as follows: 
- abstract up one layer to more of a grading rubric that the oz user fills out after the convo - there is a list of behaviors / tips with checkbox for each; if you demonstrated the behavior (like "asked permission to give feedback") i check off the box and the corresponding positive feedback is included (":+1: You asked permission to give feedback. That's always a good idea."), if you don't ask permission, I leave the box empty and the corresponding negative feedback is included (":-1: You never asked permission to give feedback. It's important to make sure that you're in a safe space to discuss development points.")
- somehow make this rubric easy to fill out during the conversation - e.g., re-combine it with the main oz conversational panel 
- correlate the specific utterances / speech acts that demonstrate the desired behavior to the actual rubric scores so that we learn to predict the grade for each session

**Comment by grahamboree** [comment]
I think for this task I'll consider the first pass part of this description, as it seems the most reasonable given the current state of the system.  Using the feedback lines that already exist in the data, I'll create a system where you can check boxes in the ui next to each line.  It'll then concatenate all the lines along with the right formatting into only one message that you can paste in slack.
