### ISSUE TITLE
Build script option to specify git branch

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#608]
The build script currently pulls from master.  This is good as a default, but would be good to have an optional argument to specify a git branch to pull from.

Use case -- we have a demo environment, and it is likely that we will often want to build from a demo branch, so that we can tweak the demo without worrying about more significant changes happening in master.

**Comment by Nesciosquid** [comment]
We're no longer using the 'demo' branch, and instead we're using staging and production branches, which I think has worked better.

There is a way to specify which version (prod vs. staging) in the build script, but I'm reluctant to make this a way to specify a particular git branch, since more things have to change between environments than just changing branches.
