### ISSUE TITLE
Local SQL AI database for devs

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#647]
Devs will individually setup local MySQL servers.

This task also encompasses creating a devtools script to populate the local mysql with data from the production RDS.

**Comment by ottermatt** [comment]
Which data should be imported from the production MySQL instance? Are we talking about restoring a snapshot of the prod db to a local MySQL instance, or do we only have to import some subset of the database? This can work either way, but it will be helpful to get a sense for what would be most useful.

To start the discussion: I suppose I favor restoring snapshots since that's the easiest thing and it doesn't require fiddling with foreign keys.

**Comment by jefforkin** [comment]
We will soon only have one RDS instance on AWS, the giantotter instance.  The dev and personal instances of databases will be local.  So yes, restore a snapshot of the prod db to a local MySQL instance.

Regarding subsets -- for the near term (3+ months, or more) while the database is still small, lets keep it simple and snapshot the whole thing.  Eventually we'll have multiple projects, and more than 50 logs per project.  At that point we may want to snapshot a specific project within the database, or even a subset of data form that project (just enough data to test things).

Last thought -- if a snapshot is easiest, let's do that.  But an alternative is to only fetch the data from domains, project, logs, log_data, labels, and tags.  Everything else gets derived from these tables, and populated via olivia_pack.py.

**Comment by ottermatt** [comment]
Restoring a snapshot may be marginally easier than restoring a subset, but
I'll definitely start with the snapshot since we could conceivably use that
in the future (e.g. to debug a production issue).

**Comment by ottermatt** [comment]
I've merged PR#40, so this is complete and closed.
