### ISSUE TITLE
OttoChat Landing Page Separate from Tools

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#703]
We want to be able to send a link that takes users directly to the OttoChat page without first landing on the WebTools page

**Comment by Nesciosquid** [comment]
You can link to OttoChat directly, but right now you need to login, and I
haven't set up the login that remembers 'where you were' before you logged
in to return you to it afterwards.

Unless you meant 'a page that is not webtools that has the chat interface
on it', which will be a little trickier.

-Aaron

On Thu, Nov 3, 2016 at 9:46 AM tomaschko notifications@github.com wrote:

Assigned #703 https://github.com/giantotter/giantotter_public/issues/703
to @Nesciosquid https://github.com/Nesciosquid.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/giantotter/giantotter_public/issues/703#event-846388992,
or mute the thread

**Comment by jefforkin** [comment]
I moved this higher in the backlog (higher priority), to indicate that we want to do whatever we need to do to be able to expose our web UI to external testers, to start regular weekly tests with Turkers and others.

Things to do include:
- On the page, surround the web app with some text indicating that this is a pre-alpha(?) tech demo.  Perhaps some text stating that it is not Ok to share this page without our permission (Dan drafts something), and some contact info.
- More ways to authenticate (FB, Twitter)
- Add separate web pages, or way to track where they were routed from, so that we can filter to find logs from Turkers separate from demos, etc.

**Comment by Nesciosquid** [comment]
I've created a separate OttoChat page at https://d187zwe76jfsqf.cloudfront.net/.

It doesn't require login, sets the 'service' of the associated session to 'Webchat (Turk)' so we'll be able to sort out the logs later.

This is *not* the page for linking to valuable clients, but rather just a  simple interface for outsourced testers.

If we want a shiny, non-tools-related page for people we want to impress, let's open another task.
