### ISSUE TITLE
Unify representation of actions

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#98]
Unify how actions are represented across logging, messaging, and AI.

**Comment by grahamboree** [comment]
For posterity:

Right now OtterInteract objects are thrown around locally for interactions, and are serialized into JSON when being sent through networking.  The issue is that OtterInteract doesn't handle every case of data that an action needs, and so we've had to add special-case properties to it to support some of the more complex interactions.  These properties are ignored in simpler actions, like GOTO.  Because we want to support a wide variety of actions, be able to play them back from recorded gameplay data, and not go crazy, we want to switch the OtterInteract structure to a JSON dictionary.  This will allow any number of arbitrary properties with arbitrary data.  The action being executed will be given the structure, and can extract the data it expects.  This JSON structure should be used for both the networking and the logging and potentially for the AI server as well (though there may be more complications with additional or augmented data that the AI server needs).
